/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as RedirectionRouteImport } from './routes/redirection'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicPromocionesRouteImport } from './routes/_public.promociones'
import { Route as PublicPostresRouteImport } from './routes/_public.postres'
import { Route as PublicPizzasRouteImport } from './routes/_public.pizzas'
import { Route as PublicPerfilRouteImport } from './routes/_public.perfil'
import { Route as PublicPedidosRouteImport } from './routes/_public.pedidos'
import { Route as PublicLocalesRouteImport } from './routes/_public.locales'
import { Route as PublicHamburguesasRouteImport } from './routes/_public.hamburguesas'
import { Route as PublicExtrasRouteImport } from './routes/_public.extras'
import { Route as PublicBebidasRouteImport } from './routes/_public.bebidas'
import { Route as PublicAcompanamientosRouteImport } from './routes/_public.acompanamientos'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectionRoute = RedirectionRouteImport.update({
  id: '/redirection',
  path: '/redirection',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPromocionesRoute = PublicPromocionesRouteImport.update({
  id: '/promociones',
  path: '/promociones',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPostresRoute = PublicPostresRouteImport.update({
  id: '/postres',
  path: '/postres',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPizzasRoute = PublicPizzasRouteImport.update({
  id: '/pizzas',
  path: '/pizzas',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPerfilRoute = PublicPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPedidosRoute = PublicPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLocalesRoute = PublicLocalesRouteImport.update({
  id: '/locales',
  path: '/locales',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHamburguesasRoute = PublicHamburguesasRouteImport.update({
  id: '/hamburguesas',
  path: '/hamburguesas',
  getParentRoute: () => PublicRoute,
} as any)
const PublicExtrasRoute = PublicExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBebidasRoute = PublicBebidasRouteImport.update({
  id: '/bebidas',
  path: '/bebidas',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAcompanamientosRoute = PublicAcompanamientosRouteImport.update({
  id: '/acompanamientos',
  path: '/acompanamientos',
  getParentRoute: () => PublicRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/checkout': typeof CheckoutRoute
  '/redirection': typeof RedirectionRoute
  '/success': typeof SuccessRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/acompanamientos': typeof PublicAcompanamientosRoute
  '/bebidas': typeof PublicBebidasRoute
  '/extras': typeof PublicExtrasRoute
  '/hamburguesas': typeof PublicHamburguesasRoute
  '/locales': typeof PublicLocalesRoute
  '/pedidos': typeof PublicPedidosRoute
  '/perfil': typeof PublicPerfilRoute
  '/pizzas': typeof PublicPizzasRoute
  '/postres': typeof PublicPostresRoute
  '/promociones': typeof PublicPromocionesRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/checkout': typeof CheckoutRoute
  '/redirection': typeof RedirectionRoute
  '/success': typeof SuccessRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/acompanamientos': typeof PublicAcompanamientosRoute
  '/bebidas': typeof PublicBebidasRoute
  '/extras': typeof PublicExtrasRoute
  '/hamburguesas': typeof PublicHamburguesasRoute
  '/locales': typeof PublicLocalesRoute
  '/pedidos': typeof PublicPedidosRoute
  '/perfil': typeof PublicPerfilRoute
  '/pizzas': typeof PublicPizzasRoute
  '/postres': typeof PublicPostresRoute
  '/promociones': typeof PublicPromocionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/redirection': typeof RedirectionRoute
  '/success': typeof SuccessRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_public/acompanamientos': typeof PublicAcompanamientosRoute
  '/_public/bebidas': typeof PublicBebidasRoute
  '/_public/extras': typeof PublicExtrasRoute
  '/_public/hamburguesas': typeof PublicHamburguesasRoute
  '/_public/locales': typeof PublicLocalesRoute
  '/_public/pedidos': typeof PublicPedidosRoute
  '/_public/perfil': typeof PublicPerfilRoute
  '/_public/pizzas': typeof PublicPizzasRoute
  '/_public/postres': typeof PublicPostresRoute
  '/_public/promociones': typeof PublicPromocionesRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/redirection'
    | '/success'
    | '/login'
    | '/register'
    | '/acompanamientos'
    | '/bebidas'
    | '/extras'
    | '/hamburguesas'
    | '/locales'
    | '/pedidos'
    | '/perfil'
    | '/pizzas'
    | '/postres'
    | '/promociones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/redirection'
    | '/success'
    | '/login'
    | '/register'
    | '/acompanamientos'
    | '/bebidas'
    | '/extras'
    | '/hamburguesas'
    | '/locales'
    | '/pedidos'
    | '/perfil'
    | '/pizzas'
    | '/postres'
    | '/promociones'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/checkout'
    | '/redirection'
    | '/success'
    | '/_auth/login'
    | '/_auth/register'
    | '/_public/acompanamientos'
    | '/_public/bebidas'
    | '/_public/extras'
    | '/_public/hamburguesas'
    | '/_public/locales'
    | '/_public/pedidos'
    | '/_public/perfil'
    | '/_public/pizzas'
    | '/_public/postres'
    | '/_public/promociones'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  RedirectionRoute: typeof RedirectionRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirection': {
      id: '/redirection'
      path: '/redirection'
      fullPath: '/redirection'
      preLoaderRoute: typeof RedirectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/promociones': {
      id: '/_public/promociones'
      path: '/promociones'
      fullPath: '/promociones'
      preLoaderRoute: typeof PublicPromocionesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/postres': {
      id: '/_public/postres'
      path: '/postres'
      fullPath: '/postres'
      preLoaderRoute: typeof PublicPostresRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pizzas': {
      id: '/_public/pizzas'
      path: '/pizzas'
      fullPath: '/pizzas'
      preLoaderRoute: typeof PublicPizzasRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/perfil': {
      id: '/_public/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PublicPerfilRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pedidos': {
      id: '/_public/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PublicPedidosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/locales': {
      id: '/_public/locales'
      path: '/locales'
      fullPath: '/locales'
      preLoaderRoute: typeof PublicLocalesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/hamburguesas': {
      id: '/_public/hamburguesas'
      path: '/hamburguesas'
      fullPath: '/hamburguesas'
      preLoaderRoute: typeof PublicHamburguesasRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/extras': {
      id: '/_public/extras'
      path: '/extras'
      fullPath: '/extras'
      preLoaderRoute: typeof PublicExtrasRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/bebidas': {
      id: '/_public/bebidas'
      path: '/bebidas'
      fullPath: '/bebidas'
      preLoaderRoute: typeof PublicBebidasRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/acompanamientos': {
      id: '/_public/acompanamientos'
      path: '/acompanamientos'
      fullPath: '/acompanamientos'
      preLoaderRoute: typeof PublicAcompanamientosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicAcompanamientosRoute: typeof PublicAcompanamientosRoute
  PublicBebidasRoute: typeof PublicBebidasRoute
  PublicExtrasRoute: typeof PublicExtrasRoute
  PublicHamburguesasRoute: typeof PublicHamburguesasRoute
  PublicLocalesRoute: typeof PublicLocalesRoute
  PublicPedidosRoute: typeof PublicPedidosRoute
  PublicPerfilRoute: typeof PublicPerfilRoute
  PublicPizzasRoute: typeof PublicPizzasRoute
  PublicPostresRoute: typeof PublicPostresRoute
  PublicPromocionesRoute: typeof PublicPromocionesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAcompanamientosRoute: PublicAcompanamientosRoute,
  PublicBebidasRoute: PublicBebidasRoute,
  PublicExtrasRoute: PublicExtrasRoute,
  PublicHamburguesasRoute: PublicHamburguesasRoute,
  PublicLocalesRoute: PublicLocalesRoute,
  PublicPedidosRoute: PublicPedidosRoute,
  PublicPerfilRoute: PublicPerfilRoute,
  PublicPizzasRoute: PublicPizzasRoute,
  PublicPostresRoute: PublicPostresRoute,
  PublicPromocionesRoute: PublicPromocionesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  RedirectionRoute: RedirectionRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
